"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { RunGraph } from "../graph/RunGraph";
import { StepThread } from "../thread/StepThread";
import type { EdgeView, StepView, ValueClick } from "../types";
import type { Diagnosis, ForkCreated, ForkEdit, ForkRequest, ForkSummary, RunDetail } from "../../lib/contract";
import { API, api } from "../../lib/api";
import { useAppContext } from "../shell/AppContext";

export function InvestigatePage({runId,startEditing=false}:{runId:string;startEditing?:boolean}) {
 const { staticBundle } = useAppContext();
 const [detail,setDetail]=useState<RunDetail|null>(null), [diagnosis,setDiagnosis]=useState<Diagnosis|null>(null), [error,setError]=useState(""), [selected,setSelected]=useState<string|null>(null), [editing,setEditing]=useState(startEditing), [kind,setKind]=useState<ForkEdit["kind"]>("override_output"), [value,setValue]=useState("{}"), [status,setStatus]=useState(""), [forkId,setForkId]=useState(""), [fork,setFork]=useState<ForkSummary|null>(null), [selectedPointer,setSelectedPointer]=useState<ValueClick|null>(null);
 const load=useCallback(()=>Promise.all([api<RunDetail>(`/runs/${encodeURIComponent(runId)}`),api<Diagnosis>(`/runs/${encodeURIComponent(runId)}/diagnosis`)]).then(([d,x])=>{setDetail(d);setDiagnosis(x);setSelected(x.responsible_addr||d.steps[0]?.addr||null)}).catch(e=>setError(e.message)),[runId]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{ if(!forkId)return; const src=new EventSource(`${API}/forks/${encodeURIComponent(forkId)}/stream`); const update=(ev:MessageEvent)=>{try{const d=JSON.parse(ev.data);if(ev.type==="step")setStatus(`Sample ${d.sample+1}: ${d.addr} · ${d.phase}${d.cache_status?` · ${d.cache_status}`:""}`); if(ev.type==="outcome")setStatus(`Sample ${d.sample+1} ${d.branch}: ${d.passed?"passed":"failed"}`);if(ev.type==="summary"){setStatus(`Replay complete · ${d.verdict||"preview"} · saved ${d.cached} cached steps`);src.close();api<ForkSummary>(`/forks/${encodeURIComponent(forkId)}`).then(setFork).catch(()=>{});load();}}catch{}}; for(const name of ["step","outcome","summary","error"])src.addEventListener(name,update as EventListener);src.onerror=()=>{api<ForkSummary>(`/forks/${encodeURIComponent(forkId)}`).then(f=>{setFork(f);if(f.status==="complete"||f.status==="error"){src.close();setStatus(`Replay ${f.status} · ${f.verdict||f.error?.message||""}`);load()}}).catch(()=>{});};return()=>src.close();},[forkId,load]);
 const steps:StepView[]=useMemo(()=>detail?.steps.map(s=>({addr:s.addr,seq:s.seq,kind:s.kind as StepView["kind"],name:s.name,role:s.agent_role,input:s.input,output:s.output,stateBefore:s.state_before,stateAfter:s.state_after,reasoning:s.reasoning.join("\n"),latencyMs:s.latency_ms,tokens:s.tokens?s.tokens.input+s.tokens.output:null,error:s.error?.message||null,cacheStatus:s.cache_status,suspicion:diagnosis?.ranking.find(x=>x.addr===s.addr)?.probability,isSuspect:diagnosis?.responsible_addr===s.addr,isVisibleFailure:diagnosis?.visible_failure_addr===s.addr,violations:s.rule_violations.map(v=>({pointer:v.citation.json_pointer||"",message:v.message}))}))||[],[detail,diagnosis]);
 const edges:EdgeView[]=useMemo(()=>detail?.edges.map((e,i)=>({id:`e${i}`,source:e.src_addr,target:e.dst_addr,kind:e.kind,label:e.key}))||[],[detail]);
 if(error&&!detail)return <div className="page"><div className="page-inner"><p className="error-box">{error}</p></div></div>;
 if(!detail||!diagnosis)return <div className="page"><div className="page-inner"><p className="muted">Loading recorded run…</p></div></div>;
 async function startFork(){if(!detail||!diagnosis)return;const step=detail.steps.find(s=>s.addr===selected);if(!step)return;let parsed:unknown;try{parsed=JSON.parse(value)}catch{setError("Edit value must be valid JSON.");return}const edit:ForkEdit={addr:step.addr,kind,value:parsed,known_good:diagnosis.proposed_fixes.some(f=>f.addr===step.addr&&f.edit.known_good)};const req:ForkRequest={base_run_id:runId,edits:[edit],mode:"cone",samples:5,control:true};setError("");setStatus("Starting paired replay…");try{const created=await api<ForkCreated>("/forks",{method:"POST",body:JSON.stringify(req)});setForkId(created.fork_id);setStatus("Replay queued…");}catch(e){setError((e as Error).message);setStatus("")}}
 const chosen=detail.steps.find(s=>s.addr===selected);
 return <div className="page investigate-page"><div className="investigate-top"><div><p className="label">{detail.run.agent} / {detail.run.run_id}</p><h1 className="h1">{detail.run.task}</h1><div className="row muted"><span className={`badge ${detail.run.status==="failed"?"badge-fail":"badge-pass"}`}>{detail.run.status}</span><span>{detail.steps.length} steps</span><span>{Math.round(detail.run.duration_ms)} ms</span><span>{detail.run.split||"unlabelled"}</span></div></div><div className="row"><Link className="btn" href={`/report/${encodeURIComponent(runId)}`}>Crash report</Link><Link className="btn" href={`/compare?a=${encodeURIComponent(runId)}`}>Compare runs</Link><button className="btn btn-primary" onClick={()=>setEditing(x=>!x)} disabled={staticBundle}>Fork and fix</button></div></div>
 <div className="investigate-work"><section className="canvas-pane"><div className="canvas-toolbar"><span className="badge badge-fail">Visible failure · {diagnosis.visible_failure_addr||"not isolated"}</span><span className="badge badge-accent">{diagnosis.abstain?"No confident culprit":`Top suspect · ${Math.round((diagnosis.ranking[0]?.probability||0)*100)}%`}</span></div><RunGraph layoutKey={runId} steps={steps} edges={edges} selected={selected} onSelect={setSelected} highlightPath={diagnosis.damage_path?.nodes.map(n=>n.addr)}/>{status&&<div className="floating-card"><div className="spread"><strong>Fork replay</strong><span className="badge badge-neutral">{fork?.verdict||"running"}</span></div><p className="muted">{status}</p>{fork?.edited_runs[0]&&<Link className="btn btn-sm" href={`/compare?a=${encodeURIComponent(runId)}&b=${encodeURIComponent(fork.edited_runs[0].run_id)}`}>Compare fork →</Link>}</div>}</section>
 <aside className="thread-pane"><div className="thread-header"><div><strong>Trace and evidence</strong><div className="faint">Select a value to follow its origin</div></div><span className="spacer"/><span className="badge badge-neutral">{detail.steps.length} steps</span></div><div className="thread-body">{diagnosis.abstain&&<div className="error-box" style={{marginBottom:14}}>{diagnosis.abstain_message}</div>}<div className="rail">{(["localize","attribute","propose","verify"] as const).map(stage=><div key={stage} className={`rail-step ${diagnosis.stages[stage]}`}>{stage}</div>)}</div>{diagnosis.reasons.slice(0,3).map((r,i)=><div className="reason" key={i}><strong>{r.text}</strong><div className="faint">{r.citation.addr} · {r.feature.group}</div></div>)}{selectedPointer&&<div className="card card-pad"><span className="label">Selected value</span><div className="mono">{selectedPointer.addr} {selectedPointer.pointer}</div><pre className="json">{JSON.stringify(selectedPointer.value,null,2)}</pre></div>}<StepThread steps={steps} selected={selected} onSelect={setSelected} view="pretty" onValueClick={setSelectedPointer}/></div></aside></div>
 {editing&&<div className="drawer-backdrop" onClick={()=>setEditing(false)}><section className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-header"><div><p className="label">Selective replay</p><h2 className="h2">Edit step and verify against a control</h2></div><button className="btn btn-sm" onClick={()=>setEditing(false)}>Close</button></div><div className="drawer-body stack"><p className="muted">The dependency cone will be replayed with five paired samples. Unchanged steps reuse exact recorded responses.</p><label className="label">Step to edit</label><select className="input" value={selected||""} onChange={e=>setSelected(e.target.value)}>{detail.steps.map(s=><option value={s.addr} key={s.addr}>{s.seq}. {s.name} · {s.addr}</option>)}</select><label className="label">Edit operation</label><select className="input" value={kind} onChange={e=>setKind(e.target.value as ForkEdit["kind"])}><option value="override_output">Replace step output</option><option value="patch_tool_result">Replace tool result</option><option value="patch_tool_args">Change tool arguments</option><option value="patch_prompt">Change prompt</option></select><label className="label">Replacement value · JSON</label><textarea className="input edit-json" value={value} onChange={e=>setValue(e.target.value)} spellCheck={false}/>{error&&<p className="error-box">{error}</p>}</div><div className="drawer-footer"><span className="muted">Control enabled · K=5</span><span className="spacer"/><button className="btn btn-primary" onClick={startFork} disabled={!chosen||staticBundle}>Start paired replay</button></div></section></div>}</div>
}
